spring:
  application:
    name: api

  # CORS
  web:
    cors:
      originPatterns: "http://localhost:4200,http://localhost:8080"
      allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
      allowedHeaders: "*"
      allowCredentials: true

  # Uploads
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  # Banco de dados
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false

  # Flyway BANCO DE DADOS
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # JSON e datas
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: America/Manaus

# Logs
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    api: DEBUG

# Configurações customizadas
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 28800000      
    refresh-expiration: 604800000

  file:
    upload-dir: ${UPLOAD_DIR:/projeto/uploads}

  email:
    subject: "Assunto Padrão"
    message: "Mensagem Padrão"

server:
  port: 8080